''' =========================================================================================== '''
# Our Chat RESTful App

''' =========================================================================================== '''
# third-party imports
from flask import render_template
from flask import request
from flask import redirect
from flask import session
from flask import jsonify
from flask import json

# local imports
from app import create_app
from app import models
from app import db
from env import FLASK_CONFIG

''' =========================================================================================== '''
# instantiate the app
app = create_app(FLASK_CONFIG)

''' =========================================================================================== '''
# define our routes

'''
Description: Render the main chat view here from templates
Input: None
Return Type: HTML, a view generated by render_template()
'''
@app.route('/')
def chat_view():
    # all_user = models.User.findall()
    the_user = models.User.query
    the_message = models.Message.query
    return render_template('home/index.html', some_user=the_user,some_message=the_message)
    #all_user = models.User.query.filter_by(id=1).first()
    #return render_template('home/index.html', all_user=all_user)

'''
Description: Render the user profile here from templates
Input: user_id
Return Type: HTML, a view generated by render_template()
'''
@app.route('/user/<int:user_id>')
def user_profile(user_id):
    the_user = models.User.query.filter_by(id=user_id).first()
    return render_template('home/userprofile.html',some_user=the_user)

'''
Description: Retrieve a collection of users from the database
Input: None
Return Type: JSON, a JSON object containing the list of users
See here for details: http://flask.pocoo.org/docs/0.12/api/#flask.json.jsonify
'''
@app.route('/users')
def user():
    #return jsonify(json_list=[i.serialize for i in models.User.query.all()])
    #return jsonify(json_list=[i.serialize for i in qryresult.all()])
    #u = User.query.get(id)
    #g = models.User.query.all()
    #return jsonify(json_list=[i.serialize for i in models.User.query.all()])
    #g = models
    #return jsonify(username=g.User.username)
    users = models.User.query.all()
    
    my_list=[]
    for user in users:
        my_dictionary = {}
        my_dictionary["username"] = user.username
        my_dictionary["password"] = user.password
        my_dictionary["src"] = user.src
        my_list.append( my_dictionary)
    return jsonify(my_list)

'''
Description: Retrieve a collection of messages from the database
Input: None
Return Type: JSON, a JSON object containing the list of messages
See here for details: http://flask.pocoo.org/docs/0.12/api/#flask.json.jsonify
'''
@app.route('/messages')
def flutter():
    messages = models.Message.query.all()
    
    my_list=[]
    for message in messages:
        my_dictionary = {}
        my_dictionary["text"] = message.text
        my_dictionary["username"] = message.username
        my_list.append( my_dictionary)
    return jsonify(my_list)



''' =========================================================================================== '''
# run the app
if __name__ == '__main__':
    app.run()
