"""empty message

Revision ID: d27aece79ca6
Revises: aa2972019e35
Create Date: 2017-03-05 21:28:17.622090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27aece79ca6'
down_revision = 'aa2972019e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=12), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
