"""empty message

Revision ID: ed481d148da4
Revises: 813219e86fbb
Create Date: 2017-03-07 13:30:52.559034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed481d148da4'
down_revision = '813219e86fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
